### ISSUE TITLE
[BUG]: DownloadBuildArtifactsV0 0.280.1 crashes with "crypto.randomUUID is not a function" on agents running the Node10 handler

### ISSUE THREAD

**Issue by OzgurAbaci** [microsoft/azure-pipelines-agent#5667]
## Task
DownloadBuildArtifactsV0 **0.280.1** (regression from 0.280.0)

## Environment
- Azure DevOps Services, classic release pipeline, deployment group job (implicit "Download artifact" step)
- Self-hosted agent **2.193.0**, Windows Server, X64
- Same pipeline and the same artifact succeed on a v4 agent (4.248.0) with the same task version 0.280.1

## Error
##[error]Unhandled: crypto.randomUUID is not a function
##[error]TypeError: crypto.randomUUID is not a function
at Vault.genKey (..._tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.280.1\node_modules\azure-pipelines-task-lib\vault.js:65:48)
at new Vault (...\azure-pipelines-task-lib\vault.js:21:14)
at Object.loadData (...\azure-pipelines-task-lib\internal.js:673:22)
at Object.<anonymous> (...\azure-pipelines-task-lib\task.js:2429:8)
at Module.compile (internal/modules/cjs/loader.js:778:30)

The task fails before doing any work. On the same agent, 0.280.0 worked on 2026-09-18; 0.280.1 fails on 2026-09-24.

## Cause
- #22489 (DownloadBuildArtifactsV0 → ArtifactEngine 2.280) changed `package-lock.json` so that `azure-pipelines-task-lib` resolves to **5.279.0** instead of 5.2.10. This comes through ArtifactEngine's `^5.278.0` dependency. The task's own `package.json` still says `^5.2.10`.
- azure-pipelines-task-lib #1180 changed `Vault.genKey()` to use `crypto.randomUUID()`, which needs **Node ≥ 14.17**.
- The 0.280.1 `task.json` still declares a **`Node10`** execution handler, and `minimumAgentVersion` was not raised. Agents that choose the Node10 handler therefore run code that can't work on Node 10. (The stack frame `internal/modules/cjs/loader.js:778` has the layout of Node 10's loader.)

## Expected
Either:
- keep the task working under the Node10 handler it declares (e.g. use a task-lib that doesn't require `crypto.randomUUID`, or fall back when it is missing), or
- drop the `Node10` handler and raise `minimumAgentVersion`, so that unsupported agents get a clear "agent too old" error instead of a runtime crash.

## Impact
Classic releases can only pin the major version (`0.*`), and the implicit deployment-group artifact download always uses V0. Affected users can't roll back to 0.280.0. As a workaround, skip the implicit download and use DownloadBuildArtifacts@1 (AgentPlugin) instead.

### Versions

See "What happened"

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server (self-hosted agent 2.193.0, X64)

### Version controll system

Azure Repos Git (not relevant: failure is in the artifact download step)

### Relevant log output

```shell
2026-09-24T07:58:20.6500337Z Agent machine name: '<agent-machine>'
2026-09-24T07:58:20.6500530Z Current agent version: '2.193.0'
2026-09-24T07:58:20.9434533Z ##[section]Starting: Download artifact - _<build-pipeline> - <artifact>
2026-09-24T07:58:20.9781474Z ==============================================================================
2026-09-24T07:58:20.9781904Z Task         : Download build artifacts
2026-09-24T07:58:20.9782210Z Description  : Download files that were saved as artifacts of a completed build
2026-09-24T07:58:20.9782446Z Version      : 0.280.1
2026-09-24T07:58:20.9782689Z Author       : Microsoft Corporation
2026-09-24T07:58:20.9783282Z ==============================================================================
2026-09-24T07:58:21.4890099Z ##[error]Unhandled: crypto.randomUUID is not a function
2026-09-24T07:58:21.4906625Z ##[error]TypeError: crypto.randomUUID is not a function
    at Vault.genKey (<agent-dir>\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.280.1\node_modules\azure-pipelines-task-lib\vault.js:65:48)
    at new Vault (<agent-dir>\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.280.1\node_modules\azure-pipelines-task-lib\vault.js:21:14)
    at Object._loadData (<agent-dir>\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.280.1\node_modules\azure-pipelines-task-lib\internal.js:673:22)
    at Object.<anonymous> (<agent-dir>\_work\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.280.1\node_modules\azure-pipelines-task-lib\task.js:2429:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2026-09-24T07:58:21.4933191Z ##[section]Finishing: Download artifact - _<build-pipeline> - <artifact>
```
