### ISSUE TITLE
pipeline tasks failed after upgrade agent to 2.174.1

### ISSUE THREAD

**Issue by mchenx** [microsoft/azure-pipelines-agent#3110]
Original issue was raised here #13541 [https://github.com/microsoft/azure-pipelines-tasks/issues/13541](url)

## Having generic issue with Azure-Pipelines/VSTS/TFS?
Everything was fine when running with vsts agent 2.153.0, but got "##[error]TypeError: _crypto.default.randomFillSync is not a function" error after upgraded to 2.160.0, according to https://developercommunity.visualstudio.com/content/problem/1148859/-cryptodefaultrandomfillsync-is-not-a-function-whe.html I upgraded the vsts agent to 2.174.1. Duing the configuration of vsts agent 2.174.1 I got "couldn't find a valid ICU package on the system." error, according to some of the microsoft docs, I set "configProperties": { "System.Globalization.Invariant": true } in the bin/Agent.Listener.runtimeconfig.json under the vsts folder and got the new vsts version installed and configured successfully. But when running a previoous build pipeline which includes docker buildAndPush task, it failed.

But I am able to run 'docker build' directly on the build server.

I read some threads which said the issue was related to centos6, but it is centos7 in my case, and my vsts agent was working fine before.

## Have you tried troubleshooting?
Tried solve the ICU issue during the installation of vsts-agent, have icu 50.2 installed via yum and restarted vsts agent service as well, didn't work. Don't know how to troubleshoot this during pipeline build.

## Agent Version and Platform
2.174.1

OS of the machine running the agent? 
CentOS 7.6
.net core runtime 2.1.22 installed
already added below setting to bin/Agent.Listener.runtimeconfig.json

"configProperties": {
      "System.Globalization.Invariant": true
    }

## Azure DevOps Type and Version
https://dev.azure.com/mvn11

## What's not working?
![image](https://user-images.githubusercontent.com/1550186/93038377-612b7300-f677-11ea-8844-59aaa0a56a55.png)

## Agent and Worker's Diagnostic Logs
![image](https://user-images.githubusercontent.com/1550186/93307824-07bc7300-f834-11ea-94db-45395c041405.png)

BTW, tried docker buildAndPush task as well as dotnet restore/build tasks, same exception.

**Comment by anatolybolshakov** [comment]
Hi @mchenx could you please try to specify System.Globalization.Invariant for Agent.Worker.runtimeconfig.json and Agent.PluginHost.runtimeconfig.json also?

**Comment by mchenx** [comment]
> Hi @mchenx could you please try to specify System.Globalization.Invariant for Agent.Worker.runtimeconfig.json and Agent.PluginHost.runtimeconfig.json also?

I don't know coz I've already upgraded the agent to 2.175.2 two months ago and the issue gone away. so I don't have such an environment to reproduce this and do experience now..

**Comment by anatolybolshakov** [comment]
Ok, thanks - I'm closing it at the moment due to lack of repro steps - please feel free to reopen it if you will face with this issue again.
